### ISSUE TITLE
Cookie header should be separated by semicolon instead of comma

### ISSUE THREAD

**Issue by hrsh7th** [mswjs/headers-polyfill#28]
First, sorry, I'm not familiar with the details of the HTTP protocol.

But I'm now having trouble with this cookie header-related problem.

After some of the investigation, the cookie header seems to be separated by `;` not `,`.

Related.
https://github.com/microsoft/reverse-proxy/issues/437
https://datatracker.ietf.org/doc/html/rfc6265#section-4.2.1

**Comment by hrsh7th** [comment]
Sorry. It seems to should not fix in this repo...

In chrome, the `Headers` class behaves the same.

```js
const h = new Headers();
h.append('cookie', 'a=b')
h.append('cookie', 'c=d');
h.forEach((k, v, p) => {
  console.log(k, v)
});
```

**Comment by hrsh7th** [comment]
So I think it should be handled in `msw` package.

**Comment by kettanaito** [comment]
Hey, @hrsh7th. 

Could you please provide more details about what you're trying to achieve, how you're using the libraries, and what is the current/expected results? It's hard for me to help you if I don't know that info. 

Ideally, I'd kindly ask you to create a minimal reproduction repo or a sandbox. If you try submitting an issue in the MSW repo, you'll find the templates to create both. 

Generally speaking, the values of a multi-value header must be separated by a semicolon. I'm not aware of headers that may have different behavior regarding this.

**Comment by hrsh7th** [comment]
OK. I'll create explanation project. I think this is important thing for msw.
