### ISSUE TITLE
Version 3.1.0 => Error: Package subpath './lib' is not defined by "exports"

### ISSUE THREAD

**Issue by giftkugel** [mswjs/headers-polyfill#41]
With the newest version 3.1.0, we are facing an error within our integration pipeline.

We are using `msw` for testing, which has `header-polyfills` as dependency.

With `header-polyfills` version 3.0.10 everything was fine, with 3.1.0 we are getting this error:

`Error: Package subpath './lib' is not defined by "exports" in /foo/node_modules/headers-polyfill/package.json`

Our setup uses TypeScript and a Lerna Monorepo with Node 16.x

**Comment by mattcosta7** [comment]
Are you importing directly from `./lib` ?  You should be able to just import from `headers-polyfill` directly instead

**Comment by kettanaito** [comment]
@mattcosta7 I don't think anyone should import things from `./lib`, even on <= 3.1. We should simply remove any mention of `./lib` from public-facing APIs.

**Comment by kettanaito** [comment]
If you are using `headers-polyfill` directly, drop any `/lib` usage:

```diff
- from "headers-polyfill/lib"
+ from "headers-polyfill"
```

If you're using MSW, update to [0.47.3](https://github.com/mswjs/msw/releases/tag/v0.47.3).

**Comment by giftkugel** [comment]
We were not using `headers-polyfill" directly, but it is used inside `msw` ... will now update to newest version of `msw` and check. 👍🏼 

Maybe it would be good if `msw` adds some tests for that. Because after the change on `headers-polyfill` some tests should fail here, not in our pipeline 😁

**Comment by giftkugel** [comment]
With `msw` 0.47.3 everything is fine again 👍🏼
