### ISSUE TITLE
Error: Package path ./lib is not exported from package

### ISSUE THREAD

**Issue by AndrewOttavianoAbb** [mswjs/headers-polyfill#43]
I just installed the `headers-polyfill` package (`v3.1.0`) and I'm getting the following error when I run the project (it's a CRA project):
>ERROR in ./node_modules/msw/lib/index.js 564:17-48
Module not found: Error: Package path ./lib is not exported from package C:\<path to app>\test-app\node_modules\headers-polyfill (see exports field in C:\<path to app>\test-app\node_modules\headers-polyfill\package.json)

It seems the following code was added in `package.json` in the `3.1.0` release and this seems to be the root cause:
```
"exports": {
  ".": {
    "types": "./lib/index.d.ts",
    "require": "./lib/index.js",
    "default": "./lib/esm/index.js"
  }
},
```

**Comment by kettanaito** [comment]
Please update to `msw0.47.3`.
