### ISSUE TITLE
There's no lib folder which is called from  /esm/package.json

### ISSUE THREAD

**Issue by oscar8x** [mswjs/headers-polyfill#44]
I'm getting this error in a project with MSW since yesterday 

Failed to compile.

./node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js
Module not found: Package path ./lib is not exported from package /node_modules/headers-polyfill (see exports field in /node_modules/headers-polyfill/package.json)

The issue is there's no lib folder and /esm/package.json couldn't get such dependencies

MSW is installed in my project since April working flawless, but since your last update (yesterday) stopped working

**Comment by kettanaito** [comment]
Hey, @oscar8x. Please update all the MSW-related modules you directly consume. Thanks.
