### ISSUE TITLE
Package subpath './lib' is not defined by "exports"

### ISSUE THREAD

**Issue by Alexintosh** [mswjs/headers-polyfill#51]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `headers-polyfill@3.1.2` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/headers-polyfill/package.json b/node_modules/headers-polyfill/package.json
index 83849d7..4eb24a3 100644
--- a/node_modules/headers-polyfill/package.json
+++ b/node_modules/headers-polyfill/package.json
@@ -10,7 +10,8 @@
       "types": "./lib/index.d.ts",
       "require": "./lib/index.js",
       "default": "./lib/index.mjs"
-    }
+    },
+    "./lib": "./lib/index.js"
   },
   "repository": "https://github.com/mswjs/headers-polyfill",
   "author": "Artem Zakharchenko",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by kettanaito** [comment]
Hey, @Alexintosh. Thanks for raising this. Do you mind opening a pull request?

**Comment by kettanaito** [comment]
I will mark this as a duplicate to #50.
