### ISSUE TITLE
3.2.0 does not handle Set-Cookie as expected

### ISSUE THREAD

**Issue by timostamm** [mswjs/headers-polyfill#60]
Here is a reproduction that sets two cookies and outputs them, once via getSetCookie, once via forEach:

<details open>
<summary>r.mjs</summary>

```js
import {Headers} from "headers-polyfill";
// import {Headers} from "undici";

const h = new Headers();
h.append(
    "set-cookie",
    "a=a; Expires=Wed, 21 Oct 2015 07:28:00 GMT",
);
h.append(
    "Set-Cookie",
    "b=b; Expires=Wed, 21 Oct 2015 07:28:00 GMT",
);

const cookies = [];
h.forEach((value, key) => {
    cookies.push(value);
});
console.log("cookies via forEach:", cookies);

console.log("cookeis via getSetCookie", h.getSetCookie())
```
</details>

```bash
$ node r.mjs
cookies via forEach: [
  'a=a; Expires=Wed, 21 Oct 2015 07:28:00 GMT, b=b; Expires=Wed, 21 Oct 2015 07:28:00 GMT'
]
cookeis via getSetCookie [
  'a=a; Expires=Wed',
  '21 Oct 2015 07:28:00 GMT',
  'b=b; Expires=Wed',
  '21 Oct 2015 07:28:00 GMT'
]
```

I would expect forEach and getSetCookie to produce the same result, an array with two entries, one for each cookie.

With undici, we get the expected result:

```bash
$ node r.mjs
cookies via forEach: [
  'a=a; Expires=Wed, 21 Oct 2015 07:28:00 GMT',
  'b=b; Expires=Wed, 21 Oct 2015 07:28:00 GMT'
]
cookeis via getSetCookie [
  'a=a; Expires=Wed, 21 Oct 2015 07:28:00 GMT',
  'b=b; Expires=Wed, 21 Oct 2015 07:28:00 GMT'
]
```

**Comment by kettanaito** [comment]
## Released: v3.2.1 🎉

This has been released in v3.2.1!

- 📄 [**Release notes**](https://github.com/mswjs/headers-polyfill/releases/tag/v3.2.1)
- 📦 [npm package](https://www.npmjs.com/package/headers-polyfill/v/3.2.1)

Make sure to always update to the latest version (`npm i headers-polyfill@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
